version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      # Опционально: если хотите позволить Jenkins запускать docker build/run:
      - /var/run/docker.sock:/var/run/docker.sock
      # Можете также примонтировать /usr/bin/docker если нужно (обычно не нужно)
    environment:
      # не отключаем setup wizard по умолчанию; при необходимости можно добавить параметры
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true


volumes:
  pgdata:
  jenkins_home:
